- name: Install VDI Apps
  hosts: all
  tasks:
  - name: Install Chocolatey and VDI Apps
    win_chocolatey:
       name: 
       - chocolatey
       - chocolatey-core.extension
       - notepadplusplus.install
       - python3
       - r
       - r.studio
       - 7zip.install
       - putty 
       - winscp
       - filezilla
       state: present 

  - name: Update fDisabledAllowList registry entry to allow vApps
    win_regedit: 
       path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList
       name: fDisabledAllowList
       data: 1
       type: dword
       state: present 
    
  - name: Create Applications registry key 
    win_regedit: 
       path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList\Applications
       state: present 
       
  - name: Add Notepad to Applications
    win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList\Applications\Notepad
       name: Name 
       data: "Notepad"
       state: present

  - name: Set Notepad execution path
    win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList\Applications\Notepad
       name: Path 
       data: C:\Windows\Notepad.exe
       state: present